### ISSUE TITLE
Incorrectly labeled a move illegal

### ISSUE THREAD

**Issue by kantuno** [qwertyquerty/ChessBot#10]
![image](https://user-images.githubusercontent.com/36526904/99885125-61f10000-2bf8-11eb-95ef-8dffa9f194a7.png)

The move was g2f1, pawn takes rook then promotes. It was labeled illegal incorrectly.

**Comment by qwertyquerty** [comment]
Notation is g2f1q or f1=Q

**Comment by qwertyquerty** [comment]
Also Jesus what a terrible move g1f1 was
